apiVersion: v1
kind: Service
metadata:
  name: db-app-service
spec:
  type: LoadBalancer
  ports:
    - name: http-port  
      protocol: TCP
      port: 80
      targetPort: 80 
    - name: mongodb-port  
      protocol: TCP
      port: 27017
      targetPort: 27017  
  selector:
    app: db-app
