apiVersion: v1
kind: Service
metadata:
  name: db-app-service
spec:
  type: LoadBalancer
  ports:
    - name: http-port  # Name for the HTTP port
      protocol: TCP
      port: 80
      targetPort: 80  # HTTP port for web interface
    - name: mongodb-port  # Name for the MongoDB port
      protocol: TCP
      port: 27017
      targetPort: 27017  # MongoDB port for the native protocol
  selector:
    app: db-app
