apiVersion: v1
kind: Pod
metadata:
  name: ollama
spec:
  containers:
  - name: model
    image: us-central1-docker.pkg.dev/sarvam-project/model-repo/model-app:v1
    resources:
      requests:
        ephemeral-storage: "4Gi"
      limits:
        ephemeral-storage: "8Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/tmp"