apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my
  template:
    metadata:
      labels:
        app: my
    spec:
      containers:
      - name: model
        image: us-central1-docker.pkg.dev/sarvam-project/model-repo/model-app:v1
        resources:
          requests:
            memory: "8Gi"
            ephemeral-storage: "8Gi"
          limits:
            memory: "16Gi"
            ephemeral-storage: "16Gi"
        volumeMounts:
        - name: ephemeral
          mountPath: "/tmp"
      volumes:
      - name: ephemeral
        emptyDir: {}
